@baseURL = http://localhost:3000
@token = U9s2!kL@x7Qp

### === AUTH ===

### 1. Registrar novo usuário
POST {{baseURL}}/api/auth/registrar
Content-Type: application/json

{
  "nome": "Klein",
  "email": "klein@gmail.com",
  "senha": "12345678"
}

### 2. Login do usuário
# Copie o token JWT do "token" da resposta e cole abaixo
POST {{baseURL}}/api/auth/login
Content-Type: application/json

{
  "email": "klein@gmail.com",
  "senha": "12345678"
}

